import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { createCodeSplittingGroups } from '../../build/chunks'

const muyaRoot = path.resolve(process.cwd(), '../src/muya')

const resolveGroupName = (id: string) => {
  const groups = createCodeSplittingGroups(muyaRoot)
  const matchedGroup = groups.find(group => group.test(id))

  return matchedGroup?.name ?? null
}

describe('code splitting groups', () => {
  it('keeps contentState support files in their intended domains', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/renderSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/renderCursorSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/renderPipelineSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeHistoryInitSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeAccessorSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeHistorySupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeInitSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeRenderLoaderSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/runtimeStateInitSupport.js'))).toBe('muya-content-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/dragDropSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/dragDropEventSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/dragDropGhostSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clipboardBlockSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clipboardCleanupSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clipboardInlineSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clipboardSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clipboardSelectionSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutClipboardSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutCopySupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutModeSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutTableSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutSelectionSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/copyCutSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/imageMarkupSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/imageInsertSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/imageMutationSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/imageReplaceSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/imageSelectionSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteClassifierSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteRuntimeLoaderSupport.js'))).toBe('muya-content-io')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/checkboxSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clickEventSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clickFormatSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clickParagraphSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/clickSelectionSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/codeBlockSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/codeBlockLanguageSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/codeBlockMutationSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/containerCreateSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/containerMathSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputAutoPairMutationSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputAutoPairDeleteSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputAutoPairInsertSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputAutoPairRuleSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputAutoPairSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputRenderSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputQuickInsertSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputSelectionMutationSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/inputTokenSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/searchMatchSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/searchReplaceSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/searchNavigateSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/searchRegexSupport.js'))).toBe('muya-content-features')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/arrowMovementSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/arrowCursorMoveSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/arrowSelectionSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/arrowTableSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/arrowTableMoveSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceBlockBoundarySupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceCellBoundarySupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceCaseSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceCodeBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceDocSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceImageCursorSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceInlineDegradeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceMergeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceFootnoteSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceBlockSpecialSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceSelectionContextSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceSelectionHandlerSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/backspaceSelectionTableSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterBlockSplitSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterBlockMiddleSplitSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterBlockEdgeSplitSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterBlockSliceSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterContextSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterFinalizeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterImageEventSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterListSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterListItemSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterParagraphSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterParagraphExitSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterParagraphTableSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterSelectionEventSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterShiftSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterTableEventSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/enterTableSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatTokenSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatOffsetSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatImageSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatSingleBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatMultiBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatInlineMutationSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatSelectionSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatTokenSelectionSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatBlockClearSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/formatActionSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphFrontMatterSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphCodeBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphCodeBlockCreateSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphCodeBlockRestoreSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphContainerSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphHtmlBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphHeadingSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphHrSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphLifecycleSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphInsertSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphDuplicateSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphDeleteSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphListTransformSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphListMenuSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphQuoteSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphTransformGuardSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphTypeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphTypeSpanSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphTypeBlockSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphSelectionSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphSelectAllSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphSelectAllRangeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphSelectAllDispatchSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/paragraphStructureMenuSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabIndentSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabIndentGuardSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabIndentMutationSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabInsertSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabFormatTokenSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabHtmlSelectorSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tabTableSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateHeadingTransforms.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateAtxHeaderSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateBlockQuoteSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateIndentCodeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateInlineRuleSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateInlineTokenConflictSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateListLineSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateListMergeSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateListSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateParagraphResetSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateSetextHeaderSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateTaskListSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateThematicBreakSupport.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/updateParagraphTransforms.js'))).toBe('muya-content-editing')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableEditContextSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableCellMutationSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableColumnMutationSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableResizeMutationSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableResizePickerSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableResizeSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableRowMutationSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableRowInsertSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableRowRemoveSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragEventSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragTransformSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragStyleSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragDataSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragColumnSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragRowSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableCreateSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableCursorSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableFigureSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionEventSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionCellsSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionLifecycleSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionMoveSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionStateSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionTableSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectionMutationSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableEditSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableDragSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableSelectSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableInitSupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/tableBlockQuerySupport.js'))).toBe('muya-content-tables')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockChildQuerySupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockBasicApiSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockInsertSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockLocationQuerySupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockMutationApiSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockRemoveSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockRemoveExemptionSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockRemoveRangeSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockRemoveMutationSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockTreeApiSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockTreeRelationApiSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockTreeTraversalApiSupport.js'))).toBe('muya-content-core')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/blockTreeQuerySupport.js'))).toBe('muya-content-core')
  })

  it('keeps markdown import support files grouped with markdown import flow', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/markdownState.js'))).toBe('muya-import-markdown')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/markdownStateTokenSupport.js'))).toBe('muya-import-markdown')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/markdownHtml.js'))).toBe('muya-import-markdown')
  })

  it('keeps generic utility support files in the utils bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/baseSupport.js'))).toBe('muya-utils')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/networkSupport.js'))).toBe('muya-utils')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/htmlSupport.js'))).toBe('muya-utils')
  })

  it('keeps async paste support files out of the initial io bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteInlineSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteFragments.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteFragmentMergeSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteHandlerSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteFinalizeSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteTargetSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteHtmlBlockSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteCodeSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteTableSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteHtmlSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteImageSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteImageMutationSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteImageFileSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteImagePathSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteTypeSupport.js'))).toBe('muya-content-paste')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/pasteSupport.js'))).toBe('muya-content-paste')
  })

  it('keeps async drag-drop image support out of the initial io bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/dragDropImageSupport.js'))).toBe('muya-content-dragdrop')
  })

  it('keeps the top-level Muya runtime helpers out of the generic core bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/index.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaClipboardApiSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaContainerSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaCommandApiSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaDocumentApiSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaDocumentSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaHistoryApiSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaInstanceApiSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaLifecycleSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaMutationSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaOptionSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaRuntimeSupport.js'))).toBe('muya-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/muyaSelectionSupport.js'))).toBe('muya-runtime')
  })

  it('keeps contentState controller wiring in the runtime bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/contentState/controllerRegistry.js'))).toBe('muya-content-runtime')
  })

  it('keeps renderer loader entry points isolated from the generic parser and utils buckets', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/renderers/index.js'))).toBe('muya-renderers')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/renderers/rendererLoadSupport.js'))).toBe('muya-renderers')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/katex.js'))).toBe('muya-renderer-katex')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/plantuml.js'))).toBe('muya-renderer-plantuml')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/sequence.js'))).toBe('muya-renderer-sequence')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/exportHtml.js'))).toBe('muya-export')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/exportMarkdown.js'))).toBe('muya-export')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/exportMarkdownNormalizeSupport.js'))).toBe('muya-export')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/exportHtmlHeaderFooterSupport.js'))).toBe('muya-export')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/utils/exportHtmlRenderSupport.js'))).toBe('muya-export')
  })

  it('keeps parser support files in the parser bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/tokenizerSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/tokenizerRuleSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/tokenizerRenderSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/referenceLabelSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/emphasisSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/htmlSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerSourceSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerBlockTokenSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerListSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerBasicFlowSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerListFlowSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerTailFlowSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/lexerFlowSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/inlineLexerSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/inlineLexerFlowSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/blockRulesBaseSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/blockRulesVariantSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/parserCoreSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/parserTokenSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/rendererBlockSupport.js'))).toBe('muya-parser')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/marked/rendererInlineSupport.js'))).toBe('muya-parser')
  })

  it('keeps parser render files in the dedicated render pipeline bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/index.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/domRenderSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/stateRenderHelpersSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/previewSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/previewObserverSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/previewRendererSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/renderBlock/renderLeafTokenSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/renderBlock/renderLeafPreviewSupport.js'))).toBe('muya-render-pipeline')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/parser/render/renderBlock/renderLeafCodeSupport.js'))).toBe('muya-render-pipeline')
  })

  it('keeps prism runtime helpers in the dedicated prism bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/prism/runtime.js'))).toBe('muya-prism-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/prism/loadLanguage.js'))).toBe('muya-prism-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/prism/runtimeSupport.js'))).toBe('muya-prism-runtime')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/prism/index.js'))).toBe('muya-prism-search')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/prism/searchSupport.js'))).toBe('muya-prism-search')
  })

  it('keeps emoji runtime helpers in the ui bucket', () => {
    expect(resolveGroupName(path.join(muyaRoot, 'lib/ui/emojis/checkSupport.js'))).toBe('muya-ui')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/ui/emojis/runtimeSupport.js'))).toBe('muya-ui-emojis')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/ui/emojis/emojisJson.json'))).toBe('muya-ui-emojis')
    expect(resolveGroupName(path.join(muyaRoot, 'lib/ui/emojiPicker/index.js'))).toBe('muya-ui-emojis')
  })

})
